import type { WebPlanItem } from "./types";

const hash = (character: string) => character.repeat(64);

export const DEMO_ITEMS: WebPlanItem[] = [
  {
    id: "demo-1",
    source: "Downloads/briefing-nexus.pdf",
    filename: "briefing-nexus.pdf",
    target: "Arquivos organizados/Documentos/briefing-nexus.pdf",
    category: "Documentos",
    size: 1_890_304,
    action: "move",
    status: "planned",
    sha256: hash("a"),
    message: "Simulação — nenhuma alteração realizada",
  },
  {
    id: "demo-2",
    source: "Downloads/hero-home.png",
    filename: "hero-home.png",
    target: "Arquivos organizados/Imagens/hero-home.png",
    category: "Imagens",
    size: 842_752,
    action: "move",
    status: "planned",
    sha256: hash("b"),
    message: "Simulação — nenhuma alteração realizada",
  },
  {
    id: "demo-3",
    source: "Downloads/hero-home-copia.png",
    filename: "hero-home-copia.png",
    target: "Arquivos organizados/Imagens/hero-home-copia.png",
    category: "Imagens",
    size: 842_752,
    action: "skip",
    status: "duplicate",
    sha256: hash("b"),
    message: "Mesmo conteúdo de Downloads/hero-home.png",
  },
  {
    id: "demo-4",
    source: "Downloads/orcamento-q3.xlsx",
    filename: "orcamento-q3.xlsx",
    target: "Arquivos organizados/Planilhas/orcamento-q3.xlsx",
    category: "Planilhas",
    size: 184_320,
    action: "move",
    status: "planned",
    sha256: hash("c"),
    message: "Simulação — nenhuma alteração realizada",
  },
  {
    id: "demo-5",
    source: "Downloads/assets-final.zip",
    filename: "assets-final.zip",
    target: "Arquivos organizados/Compactados/assets-final.zip",
    category: "Compactados",
    size: 12_582_912,
    action: "move",
    status: "planned",
    sha256: hash("d"),
    message: "Simulação — nenhuma alteração realizada",
  },
];
